server:
  port: 8081
  servlet:
    context-path: /springboot



spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/official?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://36.26.78.30:3306/official?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root@123
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.example.springboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


