server:
  port: 8888
  servlet:
    context-path: /springboot



spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://192.168.0.175:3307/gqwf_test_copy_tong
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        slave:
          url: jdbc:mysql://192.168.0.210:3306/gqwf_dev
          username: root
          password: tongzhijie
          driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_empty

#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.example.springboot.entity

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enable=true:

  #日志配置
logging:
  level:
    root: info
    com.example.springboot.mapper: debug


