server:
  port: 8081
  servlet:
    context-path: /springboot



spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.example.springboot.entity


