server:
  port: 8888
  servlet:
    context-path: /springboot



spring:
  rabbitmq:
    host: 47.111.151.105
    port: 5672
    username: guest
    password: guest
  redis:
    host: 47.111.151.105
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.111.151.105:3306/hyd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.example.springboot.entity

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enable=true:


