server:
  port: 8888
  servlet:
    context-path: /springboot



spring:
  rabbitmq:
    host: 47.111.151.105
    port: 5672
    username: guest
    password: guest
  redis:
    host: 47.111.151.105
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource: #数据源配置
    url: jdbc:mysql://192.168.0.33:3306/gqwf_dev_perfect_tong
    username: root
    password: tongzhijie
    driverClassName: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.210:9300
      cluster-name: docker-cluster

#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.example.springboot.entity

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enable=true:


